//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAccess: IEntity
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int ModuleId { get; set; }
        public bool Accessible { get; set; }
        public bool AddRecord { get; set; }
        public bool EditRecord { get; set; }
        public bool DeleteRecord { get; set; }
        public bool GenerateReport { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Module Module { get; set; }
    }
}
