//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account : IEntity
    {
       public Account()
        {
            this.AccountLogs = new HashSet<AccountLog>();
            this.ConsumableOrders = new HashSet<ConsumableOrder>();
            this.Orders = new HashSet<Order>();
            this.AccountAccesses = new HashSet<AccountAccess>();
            this.AuditTrails = new HashSet<AuditTrail>();
        }


        public int Id { get; set; }
        public string Rfid { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public UserType UserLevel { get; set; }
        public string LockCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProfileImage { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Flag { get; set; }

        public string FullName { get => $"{FirstName} {LastName}"; } 

        public virtual ICollection<AccountLog> AccountLogs { get; set; }

        public virtual ICollection<ConsumableOrder> ConsumableOrders { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public virtual ICollection<AccountAccess> AccountAccesses { get; set; }

        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
    }
}
