//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableStock
    {
        public int Id { get; set; }
        public int ConsumableId { get; set; }
        public short Stock { get; set; }
        public short DepreciatedStock { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime DateDelivered { get; set; }
    
        public virtual Consumable Consumable { get; set; }
    }
}
