//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumableOrder()
        {
            this.CosumableOrderDetails = new HashSet<CosumableOrderDetail>();
        }
    
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public OrderStatus OrderStatus { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CosumableOrderDetail> CosumableOrderDetails { get; set; }
    }
}
