//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableLog
    {
        public int Id { get; set; }
        public int ConsumableId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public short MinimumStocks { get; set; }
        public short NearExpiryAlert { get; set; }
        public bool Flag { get; set; }
        public string ActionType { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Consumable Consumable { get; set; }
    }
}
