//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int Id { get; set; }
        public int DiscountId { get; set; }
        public decimal CashReceived { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Order Order { get; set; }
    }
}
